### ISSUE TITLE
Token Vault redirect error from Dropbox or other service

### ISSUE THREAD

**Issue by nimakms** [Azure/azure-tokens#1]
After being redirected to Dropbox, authenticating there and being redirected back to `https://[token-vault-name].westcentralus.tokenvault.azure.net/redirect?state=[state]&code=[code]`, the following error page is shown.

``` xml <ApiErrorResult.ApiAppError xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Microsoft.Azure.AppService.ApiHub.Common.Results">
<Message>An error has occurred.</Message>
<SourceUri>
https://logic-te-westcentralus.azurewebsites.net/redirect?state=[state]&code=[code]
</SourceUri>
<StatusCode>BadRequest</StatusCode>
</ApiErrorResult.ApiAppError>
```
There is no actionable error message or instructions.

**Comment by nimakms** [comment]
My issue was using an incorrect Dropbox App Secret during template deployment. After redeploying with the correct value everything worked.

**Comment by joerob-msft** [comment]
This has been updated such that the error is sent back to post login redirect page as a query parameter.
