### ISSUE TITLE
AKS support?

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-tokens#9]
Hey, this looks very promising - but I'm not using AppService. Are there plans to support Kubernetes (AKS) so I can leverage this from an application running inside a pod?
Also, it wasn't clear from the doc - can we use that also for service to service authentication or is it just for authenticating users?

**Comment by joerob-msft** [comment]
@omerlh 
This service is a stand alone azure resource with REST endpoints to interact with. It does not require App Service to use. As long as your service can issue http commands, it can integrate with this service.

For service-to-service, today we support OAuth2 scenarios and some OAuth1 scenarios (twitter). I hope this helps answer our question.

**Comment by omerlh** [comment]
The readme specifies this is for AppService, this is why I'm asking. Can you please share the docs for the HTTP service?

**Comment by joerob-msft** [comment]
@omerlh You can find both the management API reference and runtime API reference in the docs folder in this repo as well.
https://github.com/Azure/azure-tokens/tree/master/docs

**Comment by omerlh** [comment]
I'm sorry, I still find it very hard to understand the big picture - what this gives me and how I can use it. Might be me...

**Comment by joerob-msft** [comment]
This service helps securely store OAuth access tokens and refresh tokens (for calling third party API's), removing a large burden from application developers with these scenarios.

**Comment by omerlh** [comment]
So it's similar to Azure Key Vault? Or is it more like Hashi Corp Vault feature that generate credentials on demand?

**Comment by joerob-msft** [comment]
Instead of secrets, this service stores access tokens and has the information needed to get a new access token from a refresh token. Users still need to login and perform a consent flow initially, but afterwards the application (through token vault) will be able to retrieve a new valid access token when needed.

**Comment by omerlh** [comment]
So let's say I'm working on a frontend application (react/angular/vue whatever), I can use this to store and process the access tokens of the users? This is highly interesting!

**Comment by itpropro** [comment]
The easiest way would be to use a Managed Identity. As far as I understand, all services that support MIs should be supported, as it‘s currently just a REST call which used an Auth token.
You could even write an Azure function to forward an MI token, but for security reasons, I would not recommend this.
